//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeUsername { get; set; }
        public string PersonCardID { get; set; }
        public string Prefix { get; set; }
        public string ThFirstName { get; set; }
        public string ThLastName { get; set; }
        public string EngFirstName { get; set; }
        public string EngLastName { get; set; }
        public string GenderCode { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string CompanyCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DivisionCode { get; set; }
        public string SubDivisionCode { get; set; }
        public string SubGroupCode { get; set; }
        public string CostCenter { get; set; }
        public Nullable<System.DateTime> DateTrain { get; set; }
        public Nullable<System.DateTime> DateAppoint { get; set; }
        public Nullable<System.DateTime> DateLastday { get; set; }
        public Nullable<System.DateTime> DateResign { get; set; }
        public string Level { get; set; }
        public string SubLevelNo { get; set; }
        public string Position { get; set; }
        public string PositionEName { get; set; }
        public string EmployeeStatusCode { get; set; }
        public string RemarkStatus { get; set; }
        public string EmployeeTypeCode { get; set; }
        public string ContactNo { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> MobileDisplay { get; set; }
        public string Email { get; set; }
        public string EmployeePicture { get; set; }
        public Nullable<System.DateTime> WorkPermitStart { get; set; }
        public Nullable<System.DateTime> WorkPermitValid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public byte[] TimpStamp { get; set; }
        public string Remark2 { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string RE_CODE { get; set; }
        public string RE_TNAME { get; set; }
        public string RE_ENAME { get; set; }
    }
}
