//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_CIC
    {
        public long CIC_ID { get; set; }
        public string Dept_No { get; set; }
        public string CIC_No { get; set; }
        public string Costcenter { get; set; }
        public Nullable<int> CICTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AstTypeID { get; set; }
        public Nullable<System.DateTime> IN_Date { get; set; }
        public Nullable<System.DateTime> OUT_Date { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string VendorContact { get; set; }
        public string Vehicle { get; set; }
        public string Brand { get; set; }
        public string License { get; set; }
        public Nullable<int> CICReasonID { get; set; }
        public Nullable<System.DateTime> Last_update { get; set; }
        public string Last_user { get; set; }
        public Nullable<System.DateTime> Last_CIC_update { get; set; }
        public string Last_CIC { get; set; }
        public Nullable<System.DateTime> Last_App_update { get; set; }
        public string Last_App { get; set; }
        public Nullable<System.DateTime> Last_PO_update { get; set; }
        public string Last_PO { get; set; }
        public Nullable<System.DateTime> Last_Sale_update { get; set; }
        public string Last_Sale { get; set; }
        public Nullable<bool> closed { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Closed_User { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Cancel_User { get; set; }
        public string Objective { get; set; }
        public Nullable<System.DateTime> CancelApp_Update { get; set; }
        public string CancelApp_User { get; set; }
        public Nullable<System.DateTime> NotApp_Update { get; set; }
        public string Notapp_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> CancelClose_Update { get; set; }
        public string CancelClose_User { get; set; }
        public string Cancelcomment { get; set; }
        public Nullable<int> CICUserID { get; set; }
        public string CIC_No_OLD { get; set; }
        public string CIC_No_REF { get; set; }
        public Nullable<bool> FlagDel { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Delete_Update { get; set; }
        public string Delete_User { get; set; }
        public string CloseRemark { get; set; }
        public Nullable<bool> CICTransfer { get; set; }
        public Nullable<System.DateTime> WaitApporveDate { get; set; }
        public string UploadUser { get; set; }
        public Nullable<System.DateTime> UploadDatetime { get; set; }
        public string EmployeeCode2 { get; set; }
        public string Last_App2 { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<bool> FlagChange { get; set; }
    }
}
