//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_CICAttach
    {
        public long CICAttachID { get; set; }
        public Nullable<long> CIC_ID { get; set; }
        public string AttachPath { get; set; }
        public string AttachFile { get; set; }
        public Nullable<System.DateTime> AttachUpdate { get; set; }
        public string AttachUser { get; set; }
        public Nullable<bool> AttachClosed { get; set; }
    }
}
