//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_CIC14InList
    {
        public long CIC14InListID { get; set; }
        public Nullable<long> CICDetailID { get; set; }
        public Nullable<bool> INFlag { get; set; }
        public Nullable<decimal> IN_Amount { get; set; }
        public Nullable<decimal> IN_Scrap { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string INUser { get; set; }
        public Nullable<System.DateTime> INUpdate { get; set; }
        public Nullable<bool> FlagApp { get; set; }
        public string UserApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string RefDoc { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string GINo { get; set; }
        public string CICNo { get; set; }
        public string CICUser { get; set; }
        public Nullable<System.DateTime> CICUpdate { get; set; }
        public Nullable<bool> FlagAppCIC { get; set; }
        public string CICApp { get; set; }
        public Nullable<System.DateTime> CICAppDate { get; set; }
    }
}
