//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CICCONTROL_SPRINGEntities2 : DbContext
    {
        public CICCONTROL_SPRINGEntities2()
            : base("name=CICCONTROL_SPRINGEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<trn_CIC> trn_CIC { get; set; }
        public virtual DbSet<trn_CICAttach> trn_CICAttach { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Vw_Approve> Vw_Approve { get; set; }
        public virtual DbSet<Vw_Manager> Vw_Manager { get; set; }
        public virtual DbSet<trn_CIC14InList> trn_CIC14InList { get; set; }
        public virtual DbSet<Vw_ApproveIN> Vw_ApproveIN { get; set; }
    
        public virtual int Send_CIC_Mail(string dept_No)
        {
            var dept_NoParameter = dept_No != null ?
                new ObjectParameter("Dept_No", dept_No) :
                new ObjectParameter("Dept_No", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Send_CIC_Mail", dept_NoParameter);
        }
    }
}
