//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long UserRolesID { get; set; }
        public string UserProfileLogon { get; set; }
        public string CompGroupCode { get; set; }
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DivisionCode { get; set; }
        public string Costcenter { get; set; }
        public Nullable<System.DateTime> LastDateTime { get; set; }
    }
}
