//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserProfileID { get; set; }
        public string UserProfileLogon { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string SignaturePath { get; set; }
        public Nullable<bool> ERFlag { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<bool> UserFlag { get; set; }
        public string LastUser { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte[] SignatureImage { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string RequestFormNo { get; set; }
    }
}
