//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ApproveIN
    {
        public long CICDetailID { get; set; }
        public long CIC14InListID { get; set; }
        public string Create_By { get; set; }
        public string Dept_No { get; set; }
        public string CICReason { get; set; }
        public string AssetList { get; set; }
        public string Model { get; set; }
        public string UnitDesc { get; set; }
        public Nullable<bool> INFlag { get; set; }
        public Nullable<decimal> IN_Amount { get; set; }
        public Nullable<decimal> IN_Scrap { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string INUser { get; set; }
        public Nullable<System.DateTime> INUpdate { get; set; }
        public Nullable<bool> FlagApp { get; set; }
        public string UserApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string Costcenter { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Actual_Amount { get; set; }
        public Nullable<bool> ScrapRet { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string Prefix { get; set; }
        public string ThFirstName { get; set; }
        public string ThLastName { get; set; }
    }
}
