//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ApproveOUT
    {
        public long CICDetailID { get; set; }
        public long CIC12OutListID { get; set; }
        public Nullable<int> Item { get; set; }
        public string AssetList { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Create_By { get; set; }
        public Nullable<decimal> Actual_Amount { get; set; }
        public string Dept_No { get; set; }
        public string Costcenter { get; set; }
        public long Expr6 { get; set; }
        public Nullable<bool> OutFlag { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<decimal> OutAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<bool> FlagApp { get; set; }
        public string UserApprove { get; set; }
        public Nullable<bool> Pay { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string RefDoc { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string OutUser { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<bool> FlagAppCIC { get; set; }
        public string UnitDesc { get; set; }
        public string Prefix { get; set; }
        public string ThFirstName { get; set; }
        public string ThLastName { get; set; }
        public Nullable<int> CICTypeID { get; set; }
        public string Prefixma { get; set; }
        public string ThFirstNamema { get; set; }
        public string ThLastNamema { get; set; }
    }
}
