//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIC_APPROVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Manager
    {
        public int UserProfileID { get; set; }
        public string UserProfileLogon { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string Costcenter { get; set; }
    }
}
